// generated by sapper build at 2020-02-11T08:38:40.109Z
process.env.NODE_ENV = process.env.NODE_ENV || 'production';
process.env.PORT = process.env.PORT || 5000;

console.log('Starting server on port ' + process.env.PORT);
require('./server/server.js');